import { createServer } from "./server/create-server.js"

const instructions = [
  "This server provides tools to interact with Microsoft Word documents in real time.",
  "Word will be visible on screen — changes happen in real time.",
  "",
  "",
  "--- GUIDANCE ---",
  "Content writing is STREAMING-ONLY: word_stream_start → word_stream_block(×N) → word_stream_end.",
  "word_stream_block supports markdown: headings, bold, italic, code, lists, tables, blockquotes, links, rules.",
  "Rich elements use word_insert_chart/image/textbox, word_set_page_region/page_numbers/watermark, word_add_bookmark/comment/footnote/hyperlink (with quiet:true for concise pipeline mode).",
  "Editing existing documents uses word_document → word_insert_at or raw word_* tools.",
  "",
  "--- STATE MACHINE ---",
  "The system can be in one of these states. ALWAYS call word_get_status to check before deciding:",
  "",
  "State 1: NO_WORD — Word.exe is not running.",
  "  → All document/content/table tools return ENGINE_NOT_RUNNING.",
  "  → Action: Restart MCP server.",
  "",
  "State 2: NO_DOC — Word is running but no document is active.",
  "  → Most content/table/formatting tools return NO_DOCUMENT.",
  "  → Actions: word_stream_start({title}) to create new, word_document({path}) to open existing.",
  "",
"State 3: DOC_ACTIVE — A document is open and ready.",
"  → All tools available. Use word_get_info / word_get_structure / word_get_cursor_info to orient.",
"  → **STREAMING sub-state** when word_stream_start..word_stream_end is active:",
"  →   doc suffix shows \"[流式会话活跃]\"; word_document/word_open/word_close/word_quit are blocked.",
"  →   Call word_stream_end first to return to normal DOC_ACTIVE.",
  "",
  "State 4: DIALOG — Word is showing a modal dialog (e.g. Save As, confirmation).",
  "  → Most tools will hang until the dialog is dismissed. Check Word window visually.",
  "  → Action: Dismiss the dialog manually in the Word window, then retry.",
  "",
  "--- FIRST PRINCIPLES: Action -> Effect ---",
  "word_get_status       Query current state. Always call first. Side effect: NONE.",
  "word_document         Switch to or open a file. Errors if file not found. Omit path for untitled.",
  "word_stream_start     Create new doc. Supports title, author, templatePath, page setup. Auto-closes existing.",
  "word_stream_block     Write markdown content block. Press Ctrl+Break to stop. Call multiple times for chapters.",
  "word_stream_end       Save, optional PDF export. Ends streaming session.",
  "word_open             Open existing file from disk. Use word_document for smart open.",
  "word_close            Close active doc. Returns to NO_DOC state.",
  "word_save             Save current doc (with .bak backup).",
  "word_save_as          Save with new path/format.",
  "word_set_font         Format selected text or set forward-typing font.",
  "word_set_paragraph    Format current paragraph (alignment, indents, spacing).",
  "word_apply_style      Apply named style (Heading 1/2/3, Normal, Title, etc.).",
  "word_select_text      Select by character range. Use word_get_cursor_info to find ranges.",
  "word_find_text        Search + position cursor at match. Returns context.",
  "word_go_to_paragraph  Navigate by 1-based paragraph index (from word_get_structure).",
  "word_insert_at        Insert markdown at semantic location (by heading/paragraph/bookmark).",
  "word_insert_table     Create table at cursor. Returns index=1 for subsequent operations.",
  "word_edit_cell        Fill/replace a table cell's content.",
  "word_undo_redo        Undo or redo recent actions.",
  "word_set_page_region  Add headers or footers to current section.",
  "word_insert_image     Embed image at cursor. File must exist on disk.",
  "word_insert_chart     Insert chart with data (column/bar/line/pie/area).",
  "word_insert_file      Insert content of another .docx at cursor (merge documents).",
  "word_get_text         Read full document text. Essential for verifying written content.",
  "word_get_paragraph    Read a specific paragraph's text by index.",
  "word_get_table_data   Extract table content as structured data (rows×columns grid).",
  "word_get_comments     List all comments in the document with author info.",
  "word_get_bookmarks    List all bookmarks in the document.",
  "word_get_lists        List all bullet/numbered lists with hierarchy.",
  "word_get_sections     List sections with page setup info (orientation, columns, page size).",
  "word_export_to_pdf    Export document to PDF (creates file on disk, doc unchanged).",
  "",
  "--- ANTI-PATTERNS: Common Mistakes ---",
  "These incorrect sequences produce NO EFFECT or WRONG RESULTS:",
  "",
  "BLOCK 1: Set font before typing",
  "  WRONG: word_set_font({size:14}) → word_stream_block('hello')",
  "  RIGHT: word_stream_block('hello') → word_select_all() → word_set_font({size:14})",
  "",
  "BLOCK 2: Find + goTo paragraph (find already moves cursor)",
  "  WRONG: word_find_text('keyword') then word_go_to_paragraph(n)",
  "  RIGHT: word_find_text('keyword') — cursor already at match, type/edit directly",
  "",
  "BLOCK 3: Format without selecting first",
  "  WRONG: word_set_font({bold:true}) — only affects NEW text after cursor",
  "  RIGHT: word_select_all() then word_set_font({bold:true})",
  "",
  "BLOCK 4: word_open vs word_document",
  "  WRONG: word_open({path}) — opens new window every time, even if already open",
  "  RIGHT: word_document({path}) — switches to open doc, or opens if not",
  "",
  "BLOCK 5: Undo after save",
  "  WRONG: word_save() → word_undo_redo({action:\"undo\"}) — undo history is cleared by save",
  "  RIGHT: word_undo_redo({action:\"undo\"}) during editing, word_save() when done",
  "",
  "BLOCK 6: word_stream_start with active document",
  "  NOTE: word_stream_start auto-closes the active document before creating new one.",
  "  If you want to EDIT existing doc, use word_document({path}) or word_open({path}) instead.",
  "",
  "BLOCK 7: Calling word_stream_block outside streaming session",
  "  WRONG: word_stream_block without word_stream_start first",
  "  RIGHT: word_stream_start → word_stream_block → word_stream_end",
  "",
  "--- STYLE PROFILE CONVENTION ---",
"最佳实践：文档格式一次性预配，内容用纯 Markdown 写，格式自动继承。",
"",
"  RIGHT (推荐):",
"    word_stream_start({",
"      title: '报告',",
"      baseStyleProfile: {",
"        'Normal':    { font:{name:'SimSun',size:12}, paragraph:{lineSpacingRule:'multiple',lineSpacing:1.5,spaceAfter:6} },",
"        'Heading 1': { font:{name:'SimHei',size:22,bold:true}, paragraph:{spaceBefore:18,spaceAfter:12} },",
"        'Heading 2': { font:{name:'SimHei',size:16,bold:true}, paragraph:{spaceBefore:12,spaceAfter:6} },",
"      }",
"    })",
"    word_stream_block('# 简介\\n\\n内容...')  ← 标题/正文自动继承样式",
"    word_stream_block('## 方法\\n\\n普通段落自动缩进...')",
"    word_stream_end()",
"",
"  WRONG (每步追加 undo，效率低 10x):",
"    word_stream_block('# Title') → word_select_all() → word_set_font() → word_set_paragraph()",
"    word_stream_block('## Section') → word_select_all() → word_set_font() → word_set_paragraph()",
"    ...每写一段追一套格式",
"",
"  NOTES:",
"  - baseStyleProfile 只支持内置样式（Normal, Heading 1~9, Title, Subtitle 等）",
"  - 每个样式可配 font（字体/字号/加粗/颜色/下划线/删除线/高亮）和 paragraph（对齐/缩进/间距/行距/边框/段前分页/与下段同页）",
"  - font.highlight: 传枚举名(如 yellow) → 荧光笔；传 hex(如 #FFF0E0) → 底纹（自动 RGB→BGR）",
"  - paragraph.borders: 支持 sides 数组指定边（默认四边），LineStyle 自动先于 ColorIndex 赋值",
"  - 配完后 word_stream_block 写入的 markdown 直接继承样式，零额外 COM 开销",
"  - 如需临时覆盖，可用 word_set_font / word_set_paragraph 调整光标后文本",
"",
"--- WORKFLOW TEMPLATES ---",
  "",
"# Create a new document from scratch",
"  1. word_stream_start({title:'My Report', author:'Author', baseStyleProfile:{'Normal':{font:{name:'Calibri',size:11}},'Heading 1':{font:{name:'Calibri',size:18,bold:true}}}}) → pre-configure styles",
"  2. word_set_properties({subject:'...', keywords:'...'}) → optional metadata",
"  3. word_set_page_region({target:'header', text:'My Report', alignment:'center', quiet:true}) → page header",
"  4. word_set_page_numbers({target:'footer', quiet:true}) → page numbers",
"  5. word_stream_block({text:'# Introduction\\n\\nContent...'}) → chapter 1 (自动继承 Heading 1 样式)",
"  6. word_stream_block({text:'## Methods\\n\\nMore content...'}) → chapter 2 (自动继承 Heading 2 样式)",
"  7. word_insert_table({rows:5, columns:3, data:[...], quiet:true}) → rich table",
"  8. word_insert_chart({type:'bar', data:[...], title:'Results', quiet:true}) → chart",
"  9. word_set_watermark({text:'DRAFT', quiet:true}) → watermark",
" 10. word_stream_end({save:true, exportPath:'C:\\\\output.pdf'}) → save + PDF",
  "",
  "# Edit an existing document",
  "  1. word_get_status({path:'C:\\\\docs\\\\file.docx'}) → confirm file exists",
  "  2. word_document({path:'C:\\\\docs\\\\file.docx'}) → opens it",
  "  3. word_get_structure() → get heading outline with paragraph indices",
  "  4. word_select_at({by:'heading', match:'Methods'}) → navigate to section",
  "  5. word_insert_at({text:'new content here', by:'heading', match:'Methods', offsetDirection:'after'})",
  "  6. word_save() → persist changes",
  "",
  "# Read / navigate a document",
  "  1. word_get_status({path:'C:\\\\docs\\\\file.docx'}) → check state",
  "  2. word_document({path:'C:\\\\docs\\\\file.docx'}) → open",
  "  3. word_get_info() → stats (pages, words, paragraphs, table count)",
  "  4. word_get_structure() → heading outline with paragraph indices",
  "  5. word_get_text() → read full text content",
  "  6. word_get_paragraph({index:5}) → read a specific paragraph",
  "  7. word_get_table_data({index:1}) → read table content as grid",
  "  8. word_get_comments() → review existing comments",
  "  9. word_get_bookmarks() → list navigation anchors",
  " 10. word_get_lists() → review list structure",
  " 11. word_get_sections() → check page layout (orientation, columns, page size)",
  " 12. word_find_text({findText:'keyword'}) → search and position cursor",
  " 13. word_export_to_pdf() → create PDF preview",
  "",
  "# Format a table",
  "  1. word_insert_table({rows:5, columns:3, data:[['H1','H2','H3'],['a','b','c']]})",
  "  2. word_apply_table_style({styleName:'Light List Accent 1'})",
  "  3. word_set_column_width({column:1, width:120}) → resize columns",
  "  4. word_set_cell_font({row:1, column:1, bold:true}) → format header",
  "  5. word_set_table_shading({color:'#E8F0FE', target:'row'}) → color header row",
  "",
  "",
  "# Merge documents",
  "  1. word_document({path:'C:\\\\main.docx'}) → open the base document",
  "  2. word_go_to({what:'end'}) → position cursor at end",
  "  3. word_insert_file({path:'C:\\\\appendix.docx'}) → insert content of another doc",
  "  4. word_insert_break({type:'page'}) → add page break before next section",
  "  5. word_insert_file({path:'C:\\\\disclaimer.docx'}) → insert another document",
  "  6. word_save_as({path:'C:\\\\merged-output.docx'}) → save the merged result",
  "",
  "--- ERROR RECOVERY ---",
  "All errors include a >> Recovery: hint with specific next steps.",
  "Common patterns:",
  "- NO_DOCUMENT → Use word_stream_start or word_document.",
  "- TABLE_NOT_FOUND → Check table count with word_get_info.",
  "- FILE_NOT_FOUND → Use word_get_status to find files, or word_stream_start.",
  "- ENGINE_TIMEOUT → Reduce operation size (fewer rows/columns, shorter text). Check Word dialogs.",
  "",
  "Path Safety:",
  "- File paths are validated against directory traversal attacks.",
  "- Only files in allowed directories can be accessed.",
  "- System directories (Windows) are blocked.",
].join("\n")

createServer({ instructions, enableHeartbeat: false, logPrefix: "word-mcp" }).catch((error) => {
  console.error("[word-mcp] Fatal error:", error)
  process.exit(1)
})
